services:
  - type: web
    name: app-gestion-repositor
    env: python
    buildCommand: pip install -r requirements.txt && cd gestion && python manage.py collectstatic --noinput
    startCommand: cd gestion && gunicorn gestion.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: SECRET_KEY
        generateValue: true
