# Generated by Django 5.2 on 2025-04-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_marca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='Proveedor',
            new_name='proveedor',
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
