# Generated by Django 5.2 on 2025-04-26 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_rename_proveedor_marca_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.marca'),
        ),
    ]
