# Generated by Django 5.2 on 2025-04-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='porcentaje_ganancia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
