# Generated by Django 5.1.7 on 2025-04-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_cliente_usuario_producto_usuario_proveedor_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen del producto', null=True, upload_to='productos/'),
        ),
    ]
