# Generated by Django 5.2 on 2025-04-28 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_venta_monto_pagado_venta_saldo_pendiente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('localidades', models.TextField(blank=True, help_text='Ingrese las localidades separadas por comas', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.zona'),
        ),
    ]
