# Generated by Django 5.1.7 on 2025-05-04 15:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_zona_cliente_zona'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('codigo_acceso', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_ganancia', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('precio_final', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('destacado', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.catalogo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'ordering': ['orden', 'producto__nombre'],
                'unique_together': {('catalogo', 'producto')},
            },
        ),
    ]
